"""
Django settings for PremiumEventosJM project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ⚠️ Esta clave está escrita en texto plano en el código. Antes de subir el
# proyecto a un repositorio público o a producción, se debe mover a una
# variable de entorno (ej. con django-environ o python-decouple) y generar
# una clave nueva, ya que esta quedó expuesta.
SECRET_KEY = 'django-insecure--&d2_@*%u)x5r_-tp22_eb_pa3yyc+z@g)y6xm@@x_551aehiu'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True muestra tracebacks detallados de errores (útil en desarrollo,
# pero es un riesgo de seguridad si se despliega así en producción).
DEBUG = True

# Vacío porque DEBUG=True lo permite (Django solo exige ALLOWED_HOSTS
# cuando DEBUG=False). Antes de desplegar en producción hay que llenarlo
# con el dominio real, ej. ['premiumeventosjm.com'].
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Apps propias del proyecto (deben ir antes o después no afecta el
    # funcionamiento, pero por convención suelen listarse primero).
    'core',              # vistas de páginas estáticas (inicio, galería, catálogo, etc.)
    'Bd_PremiumEventos',  # modelos, autenticación y lógica de cotización
    'panel_admin',        # panel de administración a medida (CRUD, historial y reportes PDF)
    # Apps internas de Django
    'django.contrib.admin',        # panel de administración
    'django.contrib.auth',         # sistema de usuarios/permisos de Django (no se usa para el login del sitio, ver Bd_PremiumEventos.views)
    'django.contrib.contenttypes', # requerido por auth/admin
    'django.contrib.sessions',     # habilita request.session, usado para guardar el login (usuario_id, nombre, rol)
    'django.contrib.messages',     # habilita los mensajes flash (messages.success/error) que se muestran en base.html
    'django.contrib.staticfiles',  # sirve los archivos de core/static/ en desarrollo
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PremiumEventosJM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PremiumEventosJM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# ⚠️ El proyecto usa MySQL, NO el archivo db.sqlite3 que viene en la raíz
# del proyecto (ese archivo es sobrante y puede eliminarse sin afectar
# nada). Para correr el proyecto localmente se necesita tener MySQL
# corriendo en 127.0.0.1:3306 con una base de datos llamada
# `premium_eventos_jm` ya creada.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            # Hace que MySQL sea más estricto validando datos (rechaza
            # inserciones/actualizaciones inválidas en vez de "arreglarlas"
            # silenciosamente, como recortar un texto muy largo).

            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (contenido subido por usuarios, ej. fotos de la galería
# cargadas desde el panel de administrador). A diferencia de STATIC_URL,
# esto no son archivos del código sino datos: por eso /media/ está en
# .gitignore y se sirve aparte (ver PremiumEventosJM/urls.py, solo en
# desarrollo con DEBUG=True; en producción lo debe servir el propio
# servidor web, ej. Nginx).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
