# Generated by Django 6.0.4 on 2026-08-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoSeleccion',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
            ],
            options={
                'db_table': 'carrito_seleccion',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono_whatsapp', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ContactoSimple',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacto_simple',
            },
        ),
        migrations.CreateModel(
            name='ItemDecoracion',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'item_decoracion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(db_column='contraseña', max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('cantidad_invitados', models.IntegerField()),
                ('tema_estilo', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.cliente')),
            ],
            options={
                'db_table': 'cotizacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_personas_aplica', models.IntegerField()),
                ('salon', models.BooleanField(default=False)),
                ('detalles', models.TextField()),
                ('evento', models.CharField(max_length=50)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_cotizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.cotizacion')),
            ],
            options={
                'db_table': 'detalle_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.carritoseleccion')),
                ('item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.itemdecoracion')),
            ],
            options={
                'db_table': 'detalle_carrito',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.usuario'),
        ),
        migrations.AddField(
            model_name='carritoseleccion',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='Bd_PremiumEventos.usuario'),
        ),
    ]
