# Generated by Django 6.0.4 on 2026-08-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_PremiumEventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoseleccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ContactoSimple',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='item',
        ),
        migrations.DeleteModel(
            name='CarritoSeleccion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleCarrito',
        ),
        migrations.DeleteModel(
            name='ItemDecoracion',
        ),
    ]
