# Generated by Django 6.0.4 on 2026-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_PremiumEventos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='correo_cliente',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_cliente',
            field=models.CharField(default='', max_length=15),
        ),
    ]
