# Generated by Django 6.0.4 on 2026-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_PremiumEventos', '0004_cotizacion_correo_cliente_cotizacion_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='correo_cliente',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_cliente',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_cliente',
            field=models.CharField(max_length=15),
        ),
    ]
