# Generated by Django 5.2.17 on 2026-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0005_alter_cotizacion_correo_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                    ("completada", "Completada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="notas_admin",
            field=models.TextField(blank=True, default=""),
        ),
    ]
