# Generated by Django 5.2.17 on 2026-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0006_cotizacion_estado_cotizacion_notas_admin"),
    ]

    operations = [
        # Se agrega SIN unique=True todavía a propósito: si ya existen
        # cotizaciones en la tabla, todas quedarían con el mismo valor
        # vacío ('') y una restricción de unicidad fallaría de inmediato.
        # La migración 0008 rellena un código distinto para cada fila
        # existente, y la 0009 recién ahí agrega unique=True.
        migrations.AddField(
            model_name="cotizacion",
            name="codigo_seguimiento",
            field=models.CharField(blank=True, default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                    ("completada", "Completada"),
                    ("pagado", "Pagado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("empleado", "Empleado"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=50,
            ),
        ),
    ]
