# Generated by Django 5.2.17 on 2026-09-21 17:28

import Bd_PremiumEventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0009_cotizacion_codigo_seguimiento_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoGaleria",
            fields=[
                ("id_foto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("matrimonio", "Matrimonio"),
                            ("15-anos", "15 Años"),
                            ("grados", "Grados"),
                            ("proms", "Proms"),
                            ("primera-comunion", "Primera Comunión"),
                            ("bautizo", "Bautizo"),
                            ("fiesta-infantil", "Fiesta infantil"),
                            ("cumpleanos", "Cumpleaños"),
                            ("baby-shower", "Baby shower"),
                            ("revelacion-de-genero", "Revelación de género"),
                            ("fiesta-empresarial", "Fiesta empresarial"),
                            ("alquiler-de-mobiliario", "Alquiler de mobiliario"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=Bd_PremiumEventos.models._ruta_imagen_galeria
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "foto_galeria",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
