# Generated by Django 5.2.17 on 2026-09-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_PremiumEventos', '0010_fotogaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotogaleria',
            name='categoria',
            field=models.CharField(choices=[('matrimonio', 'Matrimonio'), ('15-anos', '15 Años'), ('grados', 'Grados'), ('primera-comunion', 'Primera Comunión'), ('bautizo', 'Bautizo'), ('fiesta-infantil', 'Fiesta infantil'), ('cumpleanos', 'Cumpleaños'), ('baby-shower', 'Baby shower'), ('revelacion-de-genero', 'Revelación de género'), ('fiesta-empresarial', 'Fiesta empresarial'), ('alquiler-de-mobiliario', 'Alquiler de mobiliario')], max_length=50),
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='Bd_PremiumEventos.usuario')),
            ],
            options={
                'db_table': 'testimonio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
