# Generated by Django 5.2.17 on 2026-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_PremiumEventos', '0011_alter_fotogaleria_categoria_testimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')]),
        ),
    ]
