# Generated by Django 5.2.17 on 2026-09-23 00:00

import Bd_PremiumEventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0012_alter_testimonio_calificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdecoracion",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("mobiliario", "Mobiliario"),
                    ("textiles", "Textiles y Mantelería"),
                    ("decoracion", "Decoración y Ambientación"),
                ],
                default="mobiliario",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemdecoracion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Bd_PremiumEventos.models._ruta_imagen_catalogo,
            ),
        ),
        migrations.AddField(
            model_name="itemdecoracion",
            name="unidad",
            field=models.CharField(default="Unidad", max_length=50),
        ),
    ]
