# Generated by Django 5.2.17 on 2026-09-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Bd_PremiumEventos",
            "0013_itemdecoracion_categoria_itemdecoracion_imagen_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonio",
            name="activo",
        ),
    ]
