# Generated by Django 5.2.17 on 2026-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0014_remove_testimonio_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordatorioEnviado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=60, unique=True)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recordatorio_enviado",
            },
        ),
    ]
