# Generated by Django 5.2.17 on 2026-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0015_recordatorio_enviado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="motivo_rechazo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
