# Generated by Django 5.2.17 on 2026-10-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bd_PremiumEventos", "0016_cotizacion_motivo_rechazo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPrecios",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarifa_invitado_adicional",
                    models.DecimalField(decimal_places=2, default=58000, max_digits=12),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "configuracion_precios",
            },
        ),
        migrations.CreateModel(
            name="PaquetePrecio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitados", models.PositiveIntegerField(unique=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "db_table": "paquete_precio",
                "ordering": ["invitados"],
            },
        ),
    ]
